service: serverless-next

useDotenv: true

provider:
  name: aws
  runtime: nodejs16.x
  region: us-east-1
  environment:
    APP_ENV: ${sls:stage}
    AWS_BUCKET: !Ref Storage
    AWS_SQS_URL: ${construct:jobs.queueUrl}

  apiGateway:
    shouldStartNameWithService: true
    binaryMediaTypes:
      - "*/*"

resources:
  Resources:
    Storage:
      Type: AWS::S3::Bucket
    AssetsBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: next-static-site-assets

functions:
  api:
    handler: server.handler
    events:
      # Using Amazon Aws Api Gateway v2 (HTTP API)
      - httpApi: "*"
      # Using Amazon Aws Api Gateway v1 (REST API - with stage name in url)
      # - http: ANY /
      # - http: ANY /{proxy+}

plugins:
  - serverless-esbuild
  - serverless-dotenv-plugin
  - serverless-lift
  - serverless-s3-sync

package:
  individually: true
  patterns:
    - ".next"
    - "node_modules"
    - "public"
    - "_next"
    - "next.config.js"
    - "next-i18next.config.js"
    - "package.json"

custom:
  s3Sync:
    - bucketName: next-static-site-assets
      localDir: .next/static
      bucketPrefix: _next/static/

  esbuild:
    bundle: true
    minify: true
    exclude: "*"
    external:
      - "next"
  dotenv:
    exclude:
      - APP_ENV
      - AWS_BUCKET
      - AWS_SQS_URL
    required:
      env:
        - AMAZON_AWS_ACCESS_KEY_ID
        - AMAZON_AWS_ACCESS_KEY_SECRET
        - AMAZON_AWS_DEFAULT_REGION

constructs:
  jobs:
    type: queue
    worker:
      handler: server.queueReceiver
    # fifo: false
    ### The maxRetries option configures how many times each message will be retried in case of failure.
    ### maxRetries default: 3
    # maxRetries: 5
    ### Lambda will receive 5 messages at a time
    ### Batch size between 1 and 10 for FIFO queues and 10000 for standard queues.
    ### For batch size over 10, maxBatchingWindow must be set.
    ### batchSize default: 1
    # batchSize: 5
    ### SQS will wait $$ seconds (so that it can batch any messages together) before delivering to lambda
    ### maxBatchingWindow default: 0 second
    # maxBatchingWindow: 5
