service: serverless-next

useDotenv: true

provider:
  name: aws
  runtime: nodejs16.x
  region: us-east-1
  environment:
    USER_POOL: !Ref UserPool
    AWS_BUCKET: !Ref Storage
    USER_POOL_CLIENT: !Ref UserClient
    DYNAMODB_TABLE_NAME: !Ref MyDynamoDbTable
    ### DynamoDB DAX Endpoint Variable
    # DYNAMODB_DAX_ENDPOINT: !GetAtt MyDaxCluster.ClusterDiscoveryEndpoint
    APP_ENV: ${sls:stage}
    AWS_SQS_URL: ${construct:jobs.queueUrl}
    AMAZON_AWS_DEFAULT_REGION: ${self:provider.region}
    AWS_STATIC_BUCKET: next-static-site-assets # TODO [AssetsBucket] use !Ref AssetsBucket instead of fixed bucket name
  ### Auth Middleware
  # httpApi:
  #   authorizers:
  #     userAuthorization:
  #       identitySource: $request.header.Authorization
  #       issuerUrl: { "Fn::Join": ["", ["https://cognito-idp.us-east-1.amazonaws.com/", !Ref UserPool]] }
  #       audience: !Ref UserClient
  apiGateway:
    shouldStartNameWithService: true
    binaryMediaTypes:
      - "*/*"
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            # Cognito
            - cognito-idp:AdminInitiateAuth
            - cognito-idp:AdminCreateUser
            - cognito-idp:AdminSetUserPassword
            # DynamoDb
            - dynamodb:DescribeTable
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: "*"

resources:
  Resources:
    ### DynamoDB DAX IAM Role
    # MyDaxRole:
    #   Type: AWS::IAM::Role
    #   Properties:
    #     RoleName: my-dax-role
    #     AssumeRolePolicyDocument:
    #       Statement:
    #         - Effect: Allow
    #           Principal:
    #             Service: dax.amazonaws.com
    #           Action: sts:AssumeRole
    #     Policies:
    #       - PolicyName: dax-policy
    #         PolicyDocument:
    #           Statement:
    #             - Effect: Allow
    #               Action: dax:*
    #               Resource: "*"
    #     Description: String
    #     ManagedPolicyArns:
    #       - String
    #     MaxSessionDuration: Integer
    #     Path: String
    #     PermissionsBoundary: String
    #     Tags:
    #       - Tag
    Storage:
      Type: AWS::S3::Bucket
    AssetsBucket:
      Type: AWS::S3::Bucket
      Properties: # TODO [AssetsBucket]: Remove to use auto generated bucket name
        BucketName: next-static-site-assets # TODO [AssetsBucket]: Remove to use auto generated bucket name
        CorsConfiguration:
          CorsRules:
            - AllowedMethods:
                - GET
                - HEAD
              AllowedOrigins:
                - "*"
    AssetsBucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: !Ref AssetsBucket
        PolicyDocument:
          Statement:
            - Effect: Allow
              Principal: "*"
              Action: s3:GetObject
              Resource: !Sub "arn:aws:s3:::${AssetsBucket}/*"
    UserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        UserPoolName: ${self:service}-pool-${sls:stage}
        Schema:
          - Name: email
            Required: true
            Mutable: true
        Policies:
          PasswordPolicy:
            MinimumLength: 6
        AutoVerifiedAttributes: ["email"]
    UserClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        ClientName: ${self:service}-client-${sls:stage}
        GenerateSecret: false
        UserPoolId: !Ref UserPool
        AccessTokenValidity: 5
        IdTokenValidity: 5
        ExplicitAuthFlows:
          - "ADMIN_NO_SRP_AUTH"
    MyDynamoDbTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        TableName: MyDynamoDbTable
        ProvisionedThroughput:
          ReadCapacityUnits: 0
          WriteCapacityUnits: 0
        TimeToLiveSpecification:
          AttributeName: ttl
          Enabled: true
        # ContributorInsightsSpecification: ContributorInsightsSpecification
        # DeletionProtectionEnabled: Boolean
        # GlobalSecondaryIndexes:
        #   - GlobalSecondaryIndex
        # ImportSourceSpecification: ImportSourceSpecification
        # KinesisStreamSpecification: KinesisStreamSpecification
        # LocalSecondaryIndexes:
        #   - LocalSecondaryIndex
        # PointInTimeRecoverySpecification: PointInTimeRecoverySpecification
        # SSESpecification: SSESpecification
        # StreamSpecification: StreamSpecification
        # TableClass: String
        # Tags:
        #   - Tag
    ### DynamoDB DAX Cluster
    # MyDaxCluster:
    #   Type: AWS::DAX::Cluster
    #   Properties:
    #     ClusterName: MyDaxCluster
    #     IAMRoleARN: !GetAtt MyDaxRole.Arn
    #     NodeType: t2.small
    #     ReplicationFactor: 1
    #     AvailabilityZones:
    #       - String
    #     ClusterEndpointEncryptionType: String
    #     Description: String
    #     NotificationTopicARN: String
    #     ParameterGroupName: String
    #     PreferredMaintenanceWindow: String
    #     SecurityGroupIds:
    #       - String
    #     SSESpecification: SSESpecification
    #     SubnetGroupName: String
    #     Tags: Json
    RdsDBCluster:
      Type: "AWS::RDS::DBCluster"
      Properties:
        Engine: aurora-mysql
        DBClusterIdentifier: my-aurora-cluster
        EngineVersion: 5.7-compatible
        MasterUsername: AN_AuroraDB
        MasterUserPassword: "AnLab2023"
        ServerlessV2ScalingConfiguration:
          MinCapacity: 0.5
          MaxCapacity: 1
    RdsDBInstance:
      Type: "AWS::RDS::DBInstance"
      Properties:
        Engine: aurora-mysql
        DBInstanceClass: db.serverless
        DBClusterIdentifier: my-aurora-instance
functions:
  api:
    handler: server.handler
    events:
      # Using Amazon Aws Api Gateway v2 (HTTP API)
      # - httpApi:
      #     method: ANY
      #     path: /api/privateEndpoint
      #     authorizer:
      #       name: userAuthorization
      - httpApi: "*"
      # Using Amazon Aws Api Gateway v1 (REST API - with stage name in url)
      # - http: ANY /
      # - http: ANY /{proxy+}

plugins:
  - serverless-esbuild
  - serverless-dotenv-plugin
  - serverless-lift
  - serverless-s3-sync

package:
  individually: true
  patterns:
    - ".next"
    - "node_modules"
    - "public"
    - "_next"
    - "next.config.js"
    - "next-i18next.config.js"
    - "package.json"

custom:
  s3Sync:
    - bucketName: next-static-site-assets # TODO [AssetsBucket] use !Ref AssetsBucket instead of fixed bucket name
      localDir: .next/static
      bucketPrefix: _next/static/
  esbuild:
    bundle: true
    minify: true
    exclude: "*"
    external:
      - "next"
  dotenv:
    include:
      - AMAZON_AWS_ACCESS_KEY_ID
      - AMAZON_AWS_ACCESS_KEY_SECRET
    required:
      env:
        - AMAZON_AWS_ACCESS_KEY_ID
        - AMAZON_AWS_ACCESS_KEY_SECRET

constructs:
  jobs:
    type: queue
    worker:
      handler: queueWorker.handler
    # fifo: false
    ### The maxRetries option configures how many times each message will be retried in case of failure.
    ### maxRetries default: 3
    # maxRetries: 5
    ### Lambda will receive 5 messages at a time
    ### Batch size between 1 and 10 for FIFO queues and 10000 for standard queues.
    ### For batch size over 10, maxBatchingWindow must be set.
    ### batchSize default: 1
    # batchSize: 5
    ### SQS will wait $$ seconds (so that it can batch any messages together) before delivering to lambda
    ### maxBatchingWindow default: 0 second
    # maxBatchingWindow: 5
