service: serverless-next

useDotenv: true

provider:
  name: aws
  runtime: nodejs16.x
  region: us-east-1
  environment:
    APP_ENV: ${sls:stage}
    AWS_BUCKET: !Ref Storage

  apiGateway:
    shouldStartNameWithService: true
    binaryMediaTypes:
      - "*/*"

resources:
  Resources:
    Storage:
      Type: AWS::S3::Bucket

functions:
  api:
    handler: server.handler
    events:
      # Using Amazon Aws Api Gateway v2 (HTTP API)
      - httpApi: "*"
      # Using Amazon Aws Api Gateway v1 (REST API - with stage name in url)
      # - http: ANY /
      # - http: ANY /{proxy+}

plugins:
  - serverless-esbuild
  - serverless-dotenv-plugin

package:
  individually: true
  patterns:
    - ".next"
    - "node_modules"
    - "public"
    - "_next"
    - "next.config.js"
    - "next-i18next.config.js"
    - "package.json"

custom:
  esbuild:
    bundle: true
    minify: true
    exclude: "*"
    external:
      - "next"
  dotenv:
    exclude:
      - APP_ENV
      - AWS_BUCKET
    required:
      env:
        - AMAZON_AWS_ACCESS_KEY_ID
        - AMAZON_AWS_ACCESS_KEY_SECRET
